CREATE DATABASE IF NOT EXISTS kiskedvencek;

CREATE TABLE IF NOT EXISTS Befizetesek(
	BefizetID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	KezelesKoltsege INTEGER,
    RendelkezesreAllo INTEGER
);

CREATE TABLE IF NOT EXISTS FajFajta(
    FajID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Faj VARCHAR(50),
    Fajta VARCHAR(50),
    Ivar VARCHAR(10),
    Szine VARCHAR(50),
    KulonlegesIsmertetoJele VARCHAR(100),
    IvartalanitasIdopontja DATE,
    Torzskonyvezett VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS BejegyzesekKezelesek(
    FebkID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Datum DATE,
    Diagnozis VARCHAR(255),
    Terapia VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS OltasokKezelesek(
OltKezID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
EgyebVedooltasokParazita VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Gazdik(
GazdiID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
Nev VARCHAR(100),
Cim VARCHAR(255),
Telefon CHAR(9),
Email VARCHAR(100),
FOREIGN KEY (AllatokID) REFERENCES Allatok(AllatokID)
);


CREATE TABLE IF NOT EXISTS Allatok(
AllatokID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
Nev VARCHAR(100),
SzuletesiIdo DATE,
FOREIGN KEY (GazdiID) REFERENCES Gazdik(GazdiID),
FOREIGN KEY (FajID) REFERENCES FajFajta(FajID),
FOREIGN KEY (FebkID) REFERENCES BejegyzesekKezelesek(FebkID),
FOREIGN KEY (OltKezID) REFERENCES OltasokKezelesek(OltKezID)
);


CREATE TABLE IF NOT EXISTS KedvGazd(
KedvGazdID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
FOREIGN KEY (GazdiID) REFERENCES Gazdik(GazdiID),
FOREIGN KEY (AllatokID)REFERENCES Allatok(AllatokID)
);
